// Command ob-docgen writes the generated half of the documentation site.
//
// Three references in this product are already enumerated in Go, drift-tested,
// and published: the project-file schema, the loader's error codes, and the
// lifecycle failure contract. Writing them again by hand in Markdown would
// create a second source that can disagree with the first, and a published
// contract that disagrees with the loader is worse than none — it teaches the
// author something untrue and they learn to ignore it.
//
// So this program is the only writer of `site/src/content/docs/reference/`
// — the field pages, `errors.mdx` and `cli.mdx` — and of the schema published at
// `site/public/onebox.run-v1.schema.json`. Those pages carry a generated marker,
// which `--check` reads in both directions: it fails when a page differs from
// what this binary would produce, and when a marked page survives that no
// generator produces any more.
//
// `TestCommittedPagesMatchTheGenerator` runs the same comparison under
// `go test ./...`, so currency does not depend on anyone remembering a recipe.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/labstack/onebox/internal/app"
	"github.com/labstack/onebox/internal/onebox"
)

// MDX parses HTML comments as JSX, so the marker uses the MDX comment form.
const generatedMarker = "{/* Generated by cmd/ob-docgen. Do not edit by hand. */}"

func main() {
	var (
		out    string
		public string
		obBin  string
		check  bool
	)
	flag.StringVar(&out, "out", "site/src/content/docs/reference", "directory to write generated reference pages into")
	flag.StringVar(&public, "public", "site/public", "directory to publish machine-readable artifacts into")
	flag.StringVar(&obBin, "ob", "", "path to a built ob binary, for the CLI reference (default: look on PATH)")
	flag.BoolVar(&check, "check", false, "fail if the files on disk differ from what would be generated")
	flag.Parse()

	files, err := generate(obBin)
	if err != nil {
		fmt.Fprintln(os.Stderr, "ob-docgen:", err)
		os.Exit(1)
	}

	// The site publishes the schema it documents. Copying the checked-in file
	// would give the published artifact a second derivation path, one that can
	// lag the loader without the loader changing. Producing it from
	// app.JSONSchema() — the same call `ob schema` makes — keeps one.
	schema, err := app.JSONSchema()
	if err != nil {
		fmt.Fprintln(os.Stderr, "ob-docgen:", err)
		os.Exit(1)
	}
	schema = append(schema, '\n')
	publicFiles := map[string]string{"onebox.run-v1.schema.json": string(schema)}

	if check {
		if err := verify(out, files); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
		if err := verify(public, publicFiles); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
		fmt.Printf("ob-docgen: %d generated page(s) and %d published artifact(s) are current\n", len(files), len(publicFiles))
		return
	}

	for name, body := range publicFiles {
		path := filepath.Join(public, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
	}

	for name, body := range files {
		path := filepath.Join(out, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
	}
	fmt.Printf("ob-docgen: wrote %d page(s) to %s\n", len(files), out)
}

// verify compares what is on disk with what the binary would write — in both
// directions.
//
// Comparing only the files the generator would produce leaves the opposite
// failure invisible: rename a key in the registry and the old page stays
// committed, keeps its autogenerated sidebar entry, and is advertised to agents
// as shipped, while the check reports everything current. A published page for a
// block the loader no longer accepts is worse than a missing one, so the marker
// that identifies generated files is read here rather than merely written.
func verify(out string, want map[string]string) error {
	var stale []string
	for name, body := range want {
		got, err := os.ReadFile(filepath.Join(out, name))
		if err != nil {
			stale = append(stale, name+" (missing)")
			continue
		}
		if string(got) != body {
			stale = append(stale, name)
		}
	}

	orphans, err := orphanedPages(out, want)
	if err != nil {
		return err
	}
	stale = append(stale, orphans...)

	if len(stale) > 0 {
		sort.Strings(stale)
		return fmt.Errorf("generated documentation is stale — run `just docs-generate`:\n  %s", strings.Join(stale, "\n  "))
	}
	return nil
}

func orphanedPages(out string, want map[string]string) ([]string, error) {
	var orphans []string
	err := filepath.WalkDir(out, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || filepath.Ext(path) != ".mdx" {
			return nil
		}
		rel, err := filepath.Rel(out, path)
		if err != nil {
			return err
		}
		if _, expected := want[filepath.ToSlash(rel)]; expected {
			return nil
		}
		body, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if bytes.Contains(body, []byte(generatedMarker)) {
			orphans = append(orphans, filepath.ToSlash(rel)+" (orphaned: no generator produces this page — delete it)")
		}
		return nil
	})
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("cannot enumerate %s: %w", out, err)
	}
	return orphans, nil
}

func generate(obBin string) (map[string]string, error) {
	files := map[string]string{}

	schema, err := loadSchema()
	if err != nil {
		return nil, err
	}
	fieldPages, err := renderFieldPages(schema)
	if err != nil {
		return nil, err
	}
	for name, body := range fieldPages {
		files[name] = body
	}

	files["errors.mdx"] = renderErrorPage()

	cli, err := renderCLIPage(obBin)
	if err != nil {
		return nil, err
	}
	if cli != "" {
		files["cli.mdx"] = cli
	}

	return files, nil
}

// ---------------------------------------------------------------- schema ---

func loadSchema() (map[string]any, error) {
	body, err := app.JSONSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot produce the JSON Schema: %w", err)
	}
	var schema map[string]any
	if err := json.Unmarshal(body, &schema); err != nil {
		return nil, fmt.Errorf("cannot decode the JSON Schema: %w", err)
	}
	return schema, nil
}

// field is one row of a reference table: a dotted path, its type, its default
// and its description, flattened out of the schema's nesting.
type field struct {
	Path        string
	Type        string
	Enum        []string
	Default     string
	Description string
	Required    bool
}

// block is one generated page: a top-level key and every field beneath it.
type block struct {
	Key      string
	Title    string
	Summary  string
	Status   status
	ReadWhen []string
	Order    int
	Fields   []field

	// RequiredKey records that the project file must declare this key at all.
	// It is read from the schema rather than authored, because a page about a
	// mandatory block that never says so is the reference failing at its
	// first job.
	RequiredKey bool
}

// status is the honesty marker a page carries. The vocabulary is closed here so
// the registry cannot invent a fourth value that the site's content schema would
// then reject at build time.
type status string

const (
	statusShipped    status = "shipped"
	statusSchemaOnly status = "schema-only"
	statusIntentOnly status = "intent-only"
)

func knownStatuses() []status {
	return []status{statusShipped, statusSchemaOnly, statusIntentOnly}
}

// The blocks that get their own page, in the order a reader meets them.
// A key absent from here still appears, on the top-level page, so a new field
// in the Go model can never silently vanish from the documentation.
var blocks = []block{
	{Key: "workloads", Title: "workloads", Order: 10, Status: statusShipped,
		Summary: "The containers that are yours: their role, source, health, routing, prerequisites and container controls.",
		ReadWhen: []string{
			"Declaring an application, worker, daemon or job",
			"Choosing between image, build and compose as a workload source",
			"Setting replicas, resources, volumes, published ports or drain behaviour",
		}},
	{Key: "services", Title: "services", Order: 20, Status: statusShipped,
		Summary: "Supporting services Onebox runs for you — the eleven built-in drivers, their versions, settings and persistence.",
		ReadWhen: []string{
			"Adding a database, cache or queue",
			"Deciding between a managed service and a daemon workload",
		}},
	{Key: "environments", Title: "environments", Order: 30, Status: statusShipped,
		Summary: "Where the application runs, the SSH target, per-environment overrides, and the policy governing deployment there.",
		ReadWhen: []string{
			"Adding a staging or production environment",
			"Requiring local confirmation, a minimum runner version, or a migration backup report",
			"Working out which fields an environment override may change",
		}},
	{Key: "runtime", Title: "runtime", Order: 40, Status: statusShipped,
		Summary: "Project-wide environment files and the local environment-file assertions checked before the server is contacted.",
		ReadWhen: []string{
			"Wiring up environment files or SOPS-encrypted entries",
			"Requiring keys to be present before a deploy is attempted",
		}},
	{Key: "deployment", Title: "deployment", Order: 50, Status: statusShipped,
		Summary:  "Release ordering, how many releases are retained for rollback, and the migration policy.",
		ReadWhen: []string{"Changing release order, retention or migration gating"}},
	{Key: "checks", Title: "checks", Order: 60, Status: statusShipped,
		Summary:  "What must be true before a release becomes current, grouped by kind: external URLs, in-workload HTTP or exec probes, or migration revision evidence.",
		ReadWhen: []string{"Gating release activation on a health endpoint or a smoke test"}},
	{Key: "proxy", Title: "proxy", Order: 70, Status: statusShipped,
		Summary:  "Who owns the ingress proxy, which image runs it, and how TLS is resolved.",
		ReadWhen: []string{"Taking over the Traefik configuration, or turning routing off entirely"}},
	{Key: "hooks", Title: "hooks", Order: 80, Status: statusShipped,
		Summary:  "Commands run at a lifecycle seam — bootstrap, pre_release, post_release, post_deploy — or keyed by a job name to replace that job's command.",
		ReadWhen: []string{"Running a command around a deploy or a rollback"}},
	{Key: "registries", Title: "registries", Order: 90, Status: statusShipped,
		Summary:  "Named container registries and the local environment variables holding their credentials.",
		ReadWhen: []string{"Pulling from a private registry"}},
	{Key: "notifications", Title: "notifications", Order: 100, Status: statusShipped,
		Summary:  "Named webhooks that receive selected operation outcomes.",
		ReadWhen: []string{"Sending deploy outcomes to Slack, Discord or an incident tool"}},
	{Key: "observability", Title: "observability", Order: 110, Status: statusIntentOnly,
		Summary:  "Declared logging, metric and alerting intent. Validated and planned, but the local engine runs nothing continuous for it.",
		ReadWhen: []string{"Recording observability intent that another system will act on"}},
	{Key: "backup_targets", Title: "backup_targets", Order: 200, Status: statusShipped,
		Summary:  "User-owned off-host S3-compatible repositories a protected service writes its backups to. Executable for the postgres driver; every other driver refuses a policy rather than accepting one it cannot honour.",
		ReadWhen: []string{"Declaring where a database's backups go", "Understanding why Onebox refuses a backup target that shares the protected host"}},
	{Key: "external_services", Title: "external_services", Order: 210, Status: statusSchemaOnly,
		Summary:  "Typed dependencies operated outside Onebox, whose lifecycle and protection stay external. Accepted by the loader; not yet executable.",
		ReadWhen: []string{"Modelling an RDS, Neon, Supabase or Upstash dependency"}},
}

func renderFieldPages(schema map[string]any) (map[string]string, error) {
	props, _ := schema["properties"].(map[string]any)
	if props == nil {
		return nil, fmt.Errorf("the JSON Schema has no top-level properties")
	}
	required := stringSet(schema["required"])

	// `blocks` is a template, not an accumulator. Aliasing it and appending
	// through the pointers made every field permanent process state, so a second
	// call in one process emitted every row twice. Copy it first: Fields is nil
	// in the template, so append allocates fresh per call.
	local := make([]block, len(blocks))
	copy(local, blocks)

	byKey := map[string]*block{}
	for i := range local {
		byKey[local[i].Key] = &local[i]
	}

	// Anything not claimed by a block lands on the top-level page, with its whole
	// subtree, so a new key in the Go model is documented rather than merely
	// named.
	top := &block{
		Key: "top-level", Title: "Top level", Order: 1, Status: statusShipped,
		Summary: "Required keys, project-wide scalars, and the single-workload shorthand.",
		ReadWhen: []string{
			"Starting a new project file",
			"Working out which keys are required",
		},
	}

	names := make([]string, 0, len(props))
	for name := range props {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		node, _ := props[name].(map[string]any)
		if node == nil {
			return nil, fmt.Errorf("top-level key %q is not an object in the schema", name)
		}
		target := byKey[name]
		if target == nil {
			// An unclaimed key gets its own row plus everything beneath it. Only
			// emitting the row would document `routes` as a bare list and lose
			// all seven of its item fields.
			merged := collapse(node)
			target = top
			target.Fields = append(target.Fields, field{
				Path:        name,
				Type:        typeOf(merged),
				Enum:        enumOf(merged),
				Default:     defaultOf(merged),
				Description: descriptionOf(merged),
				Required:    required[name],
			})
			nested, err := walk(merged, name, 0)
			if err != nil {
				return nil, fmt.Errorf("top-level key %q: %w", name, err)
			}
			target.Fields = append(target.Fields, nested...)
			continue
		}
		// A block page is the key's subtree. The key itself is required-ness
		// worth stating, and `environments` is mandatory, so record it.
		if required[name] {
			target.RequiredKey = true
		}
		fields, err := walk(node, "", 0)
		if err != nil {
			return nil, fmt.Errorf("block %q: %w", name, err)
		}
		target.Fields = append(target.Fields, fields...)
	}

	pages := map[string]string{}
	all := []*block{top}
	for i := range local {
		all = append(all, &local[i])
	}

	for _, b := range all {
		sort.SliceStable(b.Fields, func(i, j int) bool { return b.Fields[i].Path < b.Fields[j].Path })
		name := "fields/" + b.Key + ".mdx"
		pages[name] = renderBlockPage(b)
	}
	return pages, nil
}

// maxDepth bounds the recursion. The schema is a finite tree with no cycles, so
// this is a tripwire rather than a limit: exceeding it means the model grew a
// level, and the fields below it would otherwise vanish from the reference with
// nothing to say so.
const maxDepth = 12

// walk flattens a schema node into dotted field paths. It follows the three
// shapes this schema uses: object properties, an `additionalProperties` map
// keyed by a user-chosen name, and arrays of objects. The scalar shorthand forms
// appear as `oneOf` branches, which are merged rather than listed, since an
// author wants one row per field, not one row per accepted spelling.
//
// Every shape it cannot render is an error rather than an empty result. Silence
// here is indistinguishable from "this node genuinely has no fields", which is
// how a subtree disappears from a published reference without anyone noticing.
func walk(node map[string]any, prefix string, depth int) ([]field, error) {
	if depth > maxDepth {
		return nil, fmt.Errorf("%s is nested deeper than %d levels; raise maxDepth or the fields beneath it go undocumented", prefix, maxDepth)
	}
	node = collapse(node)

	if _, ok := node["patternProperties"]; ok && !onlyExtensionPatterns(node) {
		return nil, fmt.Errorf("%s uses patternProperties for something other than `x-` extensions, which this generator does not render", prefix)
	}

	if items, ok := node["items"].(map[string]any); ok {
		return walk(items, prefix+"[]", depth+1)
	}

	if props, ok := node["properties"].(map[string]any); ok {
		required := stringSet(node["required"])
		var out []field
		names := make([]string, 0, len(props))
		for name := range props {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			child, _ := props[name].(map[string]any)
			if child == nil {
				return nil, fmt.Errorf("%s.%s is not an object in the schema", prefix, name)
			}
			path := name
			if prefix != "" {
				path = prefix + "." + name
			}
			child = collapse(child)
			nested, err := walk(child, path, depth+1)
			if err != nil {
				return nil, err
			}
			out = append(out, field{
				Path:        path,
				Type:        typeOf(child),
				Enum:        enumOf(child),
				Default:     defaultOf(child),
				Description: descriptionOf(child),
				Required:    required[name],
			})
			out = append(out, nested...)
		}
		return out, nil
	}

	if extra, ok := node["additionalProperties"].(map[string]any); ok {
		next := prefix + ".<name>"
		if prefix == "" {
			next = "<name>"
		}
		return walk(extra, next, depth+1)
	}

	return nil, nil
}

// The schema uses patternProperties only to permit `x-` extension keys, which
// carry nothing and are documented in prose rather than per-field. Any other
// pattern is a shape this generator would silently drop.
func onlyExtensionPatterns(node map[string]any) bool {
	patterns, ok := node["patternProperties"].(map[string]any)
	if !ok {
		return true
	}
	for pattern := range patterns {
		if !strings.HasPrefix(pattern, "^x-") {
			return false
		}
	}
	return true
}

// collapse merges the branches of a oneOf/anyOf/allOf into one node. The scalar
// shorthands are why these exist — `image: nginx` and `image: {reference: nginx}`
// are the same field written two ways — and an author wants one row per field,
// not one row per accepted spelling.
//
// Two rules make the merge honest, and both were learned by getting them wrong.
//
// A branch that contributes nothing but `required` is stating an alternative,
// not a requirement. `oneOf` of `{required:[build]}`, `{required:[image]}`,
// `{required:[compose]}` says "exactly one of these", and merging it published
// the first branch as unconditional — the reference contradicting the loader in
// the column that matters most. A branch that also defines `properties`
// describes a shape, and the requirements it states for its own properties are
// real, so those are kept: that is what makes `env_files[].file` required inside
// the object form while `build` is not required at all.
//
// The branch carrying `properties` wins the scalar keys. Shorthand branches are
// declared first, so first-wins gave `image` the type `string` while listing its
// object sub-fields underneath it.
func collapse(node map[string]any) map[string]any {
	for _, key := range []string{"allOf", "oneOf", "anyOf"} {
		branches, ok := node[key].([]any)
		if !ok {
			continue
		}
		merged := map[string]any{}
		for k, v := range node {
			if k != key {
				merged[k] = v
			}
		}

		collapsed := make([]map[string]any, 0, len(branches))
		for _, raw := range branches {
			if branch, ok := raw.(map[string]any); ok {
				collapsed = append(collapsed, collapse(branch))
			}
		}

		// Richest first, so the object form supplies type and properties.
		sort.SliceStable(collapsed, func(i, j int) bool {
			return branchRank(collapsed[i]) > branchRank(collapsed[j])
		})

		exclusive := key != "allOf"
		for _, branch := range collapsed {
			statesOnlyRequirements := branch["properties"] == nil
			for k, v := range branch {
				if k == "required" && exclusive && statesOnlyRequirements {
					continue
				}
				if _, taken := merged[k]; !taken {
					merged[k] = v
				}
			}
		}
		return merged
	}
	return node
}

// branchRank orders combinator branches by how much they describe. A branch with
// properties describes a shape; one with only a type describes a spelling.
func branchRank(branch map[string]any) int {
	switch {
	case branch["properties"] != nil:
		return 3
	case branch["additionalProperties"] != nil, branch["items"] != nil:
		return 2
	case branch["type"] != nil:
		return 1
	default:
		return 0
	}
}

func typeOf(node map[string]any) string {
	node = collapse(node)
	if len(enumOf(node)) > 0 {
		return "enum"
	}
	switch t := node["type"].(type) {
	case string:
		if t == "array" {
			// A list whose items are a closed set is worth naming: the page
			// otherwise says "list" for a field where only two values load.
			if items, ok := collapse(node)["items"].(map[string]any); ok {
				if values := enumOf(collapse(items)); len(values) > 0 {
					quoted := make([]string, 0, len(values))
					for _, v := range values {
						quoted = append(quoted, "`"+v+"`")
					}
					return "list of " + strings.Join(quoted, " · ")
				}
			}
			return "list"
		}
		if t == "object" {
			if _, keyed := node["additionalProperties"].(map[string]any); keyed {
				return "map"
			}
			return "object"
		}
		return t
	case []any:
		var parts []string
		for _, v := range t {
			if s, ok := v.(string); ok && s != "null" {
				parts = append(parts, s)
			}
		}
		return strings.Join(parts, " · ")
	}
	if _, ok := node["properties"]; ok {
		return "object"
	}
	return ""
}

func enumOf(node map[string]any) []string {
	raw, ok := node["enum"].([]any)
	if !ok {
		return nil
	}
	var out []string
	for _, v := range raw {
		out = append(out, fmt.Sprint(v))
	}
	return out
}

func defaultOf(node map[string]any) string {
	v, ok := node["default"]
	if !ok {
		return ""
	}
	return fmt.Sprint(v)
}

func descriptionOf(node map[string]any) string {
	s, _ := node["description"].(string)
	return strings.TrimSpace(s)
}

func stringSet(raw any) map[string]bool {
	out := map[string]bool{}
	list, ok := raw.([]any)
	if !ok {
		return out
	}
	for _, v := range list {
		if s, ok := v.(string); ok {
			out[s] = true
		}
	}
	return out
}

func renderBlockPage(b *block) string {
	var buf bytes.Buffer

	fmt.Fprintln(&buf, "---")
	fmt.Fprintf(&buf, "title: %s\n", jsonString(b.Title))
	fmt.Fprintf(&buf, "description: %s\n", jsonString(b.Summary))
	fmt.Fprintf(&buf, "summary: %s\n", jsonString(b.Summary))
	fmt.Fprintf(&buf, "status: %s\n", b.Status)
	fmt.Fprintln(&buf, "generated: true")
	fmt.Fprintf(&buf, "sidebar:\n  order: %d\n", b.Order)
	if len(b.ReadWhen) > 0 {
		fmt.Fprintln(&buf, "read_when:")
		for _, when := range b.ReadWhen {
			fmt.Fprintf(&buf, "  - %s\n", jsonString(when))
		}
	}
	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, generatedMarker)
	fmt.Fprintln(&buf)

	switch b.Status {
	case statusSchemaOnly:
		fmt.Fprintln(&buf, ":::caution[Accepted, not yet executable]")
		fmt.Fprintln(&buf, "The loader validates this block and it is published in the JSON Schema, so your")
		fmt.Fprintln(&buf, "editor will complete it. The behaviour behind it is an open proposal. Declaring")
		fmt.Fprintln(&buf, "it changes nothing on the target.")
		fmt.Fprintln(&buf, ":::")
		fmt.Fprintln(&buf)
	case statusIntentOnly:
		fmt.Fprintln(&buf, ":::note[Intent only]")
		fmt.Fprintln(&buf, "These values are validated and carried into plans, but the local engine runs no")
		fmt.Fprintln(&buf, "continuous collectors or alert managers. Status reports them as declared, not")
		fmt.Fprintln(&buf, "managed.")
		fmt.Fprintln(&buf, ":::")
		fmt.Fprintln(&buf)
	case statusShipped:
	}

	if b.RequiredKey {
		fmt.Fprintf(&buf, ":::caution[`%s` is required]\n", b.Key)
		fmt.Fprintf(&buf, "A project file that does not declare `%s` fails to load.\n", b.Key)
		fmt.Fprintln(&buf, ":::")
		fmt.Fprintln(&buf)
	}

	fmt.Fprintln(&buf, "This page is generated from the same Go declarations the loader enforces, so it")
	fmt.Fprintln(&buf, "cannot drift from what `ob validate` accepts.")
	fmt.Fprintln(&buf)

	if len(b.Fields) == 0 {
		fmt.Fprintln(&buf, "This block declares no fields.")
		return buf.String()
	}

	// Every row is a dotted path, so the bare field name is never a token on
	// its own. Site search then ranks a passing mention in a guide above the
	// reference page that actually defines the field — and for a name used
	// nowhere else, returns nothing at all. This index gives each leaf name one
	// clean occurrence, and doubles as a way to skim an eighty-row page.
	if names := leafNames(b.Fields); len(names) > 0 {
		fmt.Fprintln(&buf, "## Fields on this page")
		fmt.Fprintln(&buf)
		quoted := make([]string, 0, len(names))
		for _, name := range names {
			quoted = append(quoted, "`"+name+"`")
		}
		fmt.Fprintln(&buf, strings.Join(quoted, " · "))
		fmt.Fprintln(&buf)
		fmt.Fprintln(&buf, "## Reference")
		fmt.Fprintln(&buf)
	}

	fmt.Fprintln(&buf, "| Field | Type | Default | What it does |")
	fmt.Fprintln(&buf, "| --- | --- | --- | --- |")
	for _, f := range b.Fields {
		fmt.Fprintf(&buf, "| `%s`%s | %s | %s | %s |\n",
			f.Path,
			requiredMark(f.Required),
			typeCell(f),
			defaultCell(f),
			escapeCell(f.Description),
		)
	}
	// The legend only means something when a row carries the marker. Printing it
	// on a page with no required fields invites the reader to look for one.
	for _, f := range b.Fields {
		if f.Required {
			fmt.Fprintln(&buf)
			fmt.Fprintln(&buf, "`*` marks a field that is required within its own object.")
			break
		}
	}

	return buf.String()
}

// leafNames reduces the dotted paths to the distinct field names an author
// would actually search for, dropping the `<name>` map placeholder and the
// `[]` array marker that carry no meaning on their own.
func leafNames(fields []field) []string {
	seen := map[string]bool{}
	var out []string
	for _, f := range fields {
		parts := strings.Split(f.Path, ".")
		leaf := strings.TrimSuffix(parts[len(parts)-1], "[]")
		if leaf == "" || leaf == "<name>" || seen[leaf] {
			continue
		}
		seen[leaf] = true
		out = append(out, leaf)
	}
	sort.Strings(out)
	return out
}

func requiredMark(required bool) string {
	if required {
		return " `*`"
	}
	return ""
}

func typeCell(f field) string {
	if len(f.Enum) > 0 {
		quoted := make([]string, 0, len(f.Enum))
		for _, v := range f.Enum {
			quoted = append(quoted, "`"+v+"`")
		}
		return strings.Join(quoted, " · ")
	}
	if f.Type == "" {
		return "—"
	}
	return f.Type
}

func defaultCell(f field) string {
	if f.Default == "" {
		return "—"
	}
	return "`" + f.Default + "`"
}

func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.Join(strings.Fields(s), " ")
	if s == "" {
		return "—"
	}
	return s
}

func jsonString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

// ---------------------------------------------------------------- errors ---

func renderErrorPage() string {
	var buf bytes.Buffer

	summary := "Every typed failure code in the contract: the loader's validation codes and the CLI and engine's operation codes, all of which are reachable, and the lifecycle failure contract, where a row marked reserved is one no path raises yet."

	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf, `title: Error codes`)
	fmt.Fprintf(&buf, "description: %s\n", jsonString(summary))
	fmt.Fprintf(&buf, "summary: %s\n", jsonString(summary))
	fmt.Fprintln(&buf, "status: shipped")
	fmt.Fprintln(&buf, "generated: true")
	fmt.Fprintln(&buf, "sidebar:\n  order: 300")
	fmt.Fprintln(&buf, "read_when:")
	fmt.Fprintln(&buf, `  - "A command failed and you have a code but not a cause"`)
	fmt.Fprintln(&buf, `  - "Branching on a failure programmatically instead of parsing a message"`)
	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, generatedMarker)
	fmt.Fprintln(&buf)

	fmt.Fprintln(&buf, "A code is a promise: it names a kind of failure that keeps meaning the same thing")
	fmt.Fprintln(&buf, "across releases. Branch on the code, never on the sentence.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "## Validation codes")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "Adding one is a deliberate act. A test refuses any code the loader emits that is")
	fmt.Fprintln(&buf, "not enumerated, and any enumerated code that nothing emits, so this table cannot")
	fmt.Fprintln(&buf, "drift in either direction.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "Emitted while loading and checking the project file. Each failure carries the")
	fmt.Fprintln(&buf, "code, the path that produced it, and where possible the line and the resolving")
	fmt.Fprintln(&buf, "command.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "| Code | Means |")
	fmt.Fprintln(&buf, "| --- | --- |")
	for _, code := range app.ErrorCodes() {
		meaning, _ := app.ErrorCodeMeaning(code)
		fmt.Fprintf(&buf, "| `%s` | %s |\n", code, escapeCell(meaning))
	}
	fmt.Fprintln(&buf)

	fmt.Fprintln(&buf, "## Operation codes")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "Raised while a command runs, rather than while the project file is read. These")
	fmt.Fprintln(&buf, "are the codes a deploy, a rollback, a secret rotation or an audited exec puts in")
	fmt.Fprintln(&buf, "the `error.code` field, so they are the set to branch on when automating.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "A blank command is deliberate: some failures have no honest Onebox command that")
	fmt.Fprintln(&buf, "resolves them. A local artifact that could not be written is fixed on the")
	fmt.Fprintln(&buf, "filesystem, not by running the tool again. An angle-bracketed command names a")
	fmt.Fprintln(&buf, "step to complete rather than a line to run verbatim.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "| Code | Means | Guidance role | Command |")
	fmt.Fprintln(&buf, "| --- | --- | --- | --- |")
	for _, code := range onebox.OperationFailureCodes() {
		failure, ok := onebox.OperationFailureFor(code)
		if !ok {
			panic(fmt.Sprintf("operation code %q does not resolve", code))
		}
		role, command := "—", "—"
		if failure.Command != "" {
			role = failure.GuidanceRole()
			command = "`" + failure.Command + "`"
		}
		fmt.Fprintf(&buf, "| `%s` | %s | %s | %s |\n", code, escapeCell(failure.Message), role, escapeCell(command))
	}
	fmt.Fprintln(&buf)

	fmt.Fprintln(&buf, "## Lifecycle failure codes")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, ":::caution[Most of these are still reserved]")
	fmt.Fprintln(&buf, "These codes are defined and drift-tested in the binary. Backup, restore and drill")
	fmt.Fprintln(&buf, "are executable for the postgres driver; the rest are not. A row marked **reserved** is one no")
	fmt.Fprintln(&buf, "path raises today: the code is fixed so it stays stable when the capability")
	fmt.Fprintln(&buf, "lands, but you cannot cause it. The set is computed from the source, not")
	fmt.Fprintln(&buf, "maintained by hand.")
	fmt.Fprintln(&buf, ":::")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "The failure contract shared by plans, event streams, terminal results, status and")
	fmt.Fprintln(&buf, "doctor. Each carries a stable code and one safe command in its semantic role; diagnostic")
	fmt.Fprintln(&buf, "detail stays in restricted local evidence, never in the public record.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "| Code | Reachable | Means | Guidance role | Command |")
	fmt.Fprintln(&buf, "| --- | --- | --- | --- | --- |")
	for _, code := range onebox.LifecycleFailureCodes() {
		// A code that will not resolve is a defect in the contract, not a row to
		// drop: a shorter table is one nobody can tell is incomplete.
		failure, err := onebox.NewLifecycleFailure(code)
		if err != nil {
			panic(fmt.Sprintf("lifecycle code %q does not resolve: %v", code, err))
		}
		reach := "yes"
		if onebox.LifecycleFailureReserved(code) {
			reach = "reserved"
		}
		fmt.Fprintf(&buf, "| `%s` | %s | %s | %s | `%s` |\n", code, reach, escapeCell(failure.Message), failure.GuidanceRole(), failure.GuidanceCommand())
	}

	return buf.String()
}

// ------------------------------------------------------------------- CLI ---

// renderCLIPage asks the built binary to describe itself. The root command is
// unexported in package main, so shelling out is what keeps the CLI reference
// generated rather than transcribed.
//
// A missing binary is a failure, not a reason to skip. Skipping removed the page
// from the set `verify` compares, so `--check` reported everything current while
// the committed CLI reference could say anything at all — the gate answering
// "yes" to a question it had not asked.
func renderCLIPage(obBin string) (string, error) {
	if obBin == "" {
		found, err := exec.LookPath("ob")
		if err != nil {
			return "", fmt.Errorf("no ob binary found on PATH: the CLI reference cannot be generated or verified — build it with `just build`, or pass --ob: %w", err)
		}
		obBin = found
	}

	root, err := help(obBin)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	summary := "Every ob command, its help text and its flags, taken from the binary itself."

	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf, "title: CLI commands")
	fmt.Fprintf(&buf, "description: %s\n", jsonString(summary))
	fmt.Fprintf(&buf, "summary: %s\n", jsonString(summary))
	fmt.Fprintln(&buf, "status: shipped")
	fmt.Fprintln(&buf, "generated: true")
	fmt.Fprintln(&buf, "sidebar:\n  order: 200")
	fmt.Fprintln(&buf, "read_when:")
	fmt.Fprintln(&buf, `  - "Looking up what a command does, or which flags it takes"`)
	fmt.Fprintln(&buf, `  - "Deciding whether a command contacts the server or changes it"`)
	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, generatedMarker)
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "Generated from the binary, so it cannot describe a flag the CLI does not have.")
	fmt.Fprintln(&buf, "`ob <command> --help` is the same text.")
	fmt.Fprintln(&buf)

	// Five commands change nothing, and their names do not say how they differ.
	// The axis is what each one reads, which is the question an operator is
	// actually asking when they pick between them.
	fmt.Fprintln(&buf, "## Which command changes nothing")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "Many commands change nothing — `status`, `logs`, `audit`, `schema`, `version` and `canonical` all")
	fmt.Fprintln(&buf, "just report. These five are the ones that get confused with each other, because each one")
	fmt.Fprintln(&buf, "answers \"would this deploy work?\" from a different place.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "| Command | Reads | Contacts the server |")
	fmt.Fprintln(&buf, "| --- | --- | --- |")
	fmt.Fprintln(&buf, "| `ob validate` | the project file | no |")
	fmt.Fprintln(&buf, "| `ob preview` | the runtime it would generate | no |")
	fmt.Fprintln(&buf, "| `ob doctor` | this runner, its local SSH agent, and the environment's policy | no |")
	fmt.Fprintln(&buf, "| `ob preflight` | the server's readiness to accept a deploy | yes |")
	fmt.Fprintln(&buf, "| `ob plan` | the project, the server, and writes a plan artifact | yes |")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "`ob plan` is the only one of the five that writes a file, and it writes it locally.")
	fmt.Fprintln(&buf)

	fmt.Fprintln(&buf, "## ob")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "```")
	fmt.Fprintln(&buf, strings.TrimRight(root, "\n"))
	fmt.Fprintln(&buf, "```")
	fmt.Fprintln(&buf)

	names, err := subcommands(root)
	if err != nil {
		return "", fmt.Errorf("reading the root command list: %w", err)
	}
	for _, name := range names {
		if err := renderCommand(&buf, obBin, name, 2); err != nil {
			return "", err
		}
	}

	return buf.String(), nil
}

// renderCommand emits one command and everything beneath it. It recurses rather
// than unrolling a fixed number of levels: the previous two-level version could
// never describe `ob a b c`, and the only thing that would have noticed was a
// test in another package reporting it as stale documentation.
func renderCommand(buf *bytes.Buffer, obBin, name string, level int) error {
	body, err := help(obBin, strings.Fields(name)...)
	if err != nil {
		return err
	}

	fmt.Fprintf(buf, "%s ob %s\n\n", strings.Repeat("#", level), name)
	fmt.Fprintln(buf, "```")
	fmt.Fprintln(buf, strings.TrimRight(body, "\n"))
	fmt.Fprintln(buf, "```")
	fmt.Fprintln(buf)

	// A leaf command prints no command section, which is not a parse failure.
	nested, err := subcommands(body)
	if err != nil {
		return nil
	}
	for _, child := range nested {
		if err := renderCommand(buf, obBin, name+" "+child, level+1); err != nil {
			return err
		}
	}
	return nil
}

// help runs `ob <args> --help` and insists the answer is about the command that
// was asked for.
//
// Cobra answers an unknown command with the *root* help and exit 0, so a name
// misread out of a help listing would otherwise be published as a real command
// whose body is the root help. Tolerating a non-zero exit whenever anything
// reached stdout had the same shape: a truncated or half-written help became
// documentation.
func help(bin string, args ...string) (string, error) {
	cmd := exec.Command(bin, append(args, "--help")...)
	cmd.Env = append(os.Environ(), "NO_COLOR=1")
	var out, errOut bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &errOut
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("`ob %s --help` failed: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(errOut.String()))
	}
	if len(args) > 0 {
		want := "ob " + strings.Join(args, " ")
		if !strings.Contains(out.String(), want) {
			return "", fmt.Errorf("`%s --help` did not describe %q: the command does not exist, or cobra's help template changed", want, want)
		}
	}
	return out.String(), nil
}

// subcommands reads the command sections cobra prints. Parsing help output is
// coarse, but it is the only view of the command tree available from outside
// package main.
//
// A help text with no command section at all returns an error rather than an
// empty list. The two are indistinguishable to the caller otherwise, and the
// difference is "this is a leaf command" versus "cobra's template changed and
// the entire reference is about to be published empty". Blank lines do not end
// the scan, because command groups are separated by them.
func subcommands(helpText string) ([]string, error) {
	var out []string
	seen := map[string]bool{}
	sawSection := false
	inSection := false

	for _, line := range strings.Split(helpText, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasSuffix(trimmed, "Commands:") {
			sawSection, inSection = true, true
			continue
		}
		if !inSection {
			continue
		}
		if trimmed == "" {
			// Cobra separates command groups with a blank line; the section is
			// only over when unindented text arrives.
			continue
		}
		if !strings.HasPrefix(line, " ") {
			inSection = false
			continue
		}
		fields := strings.Fields(trimmed)
		if len(fields) == 0 {
			continue
		}
		name := fields[0]
		// Cobra generates these two; they are not ours to document.
		if name == "help" || name == "completion" || seen[name] {
			continue
		}
		seen[name] = true
		out = append(out, name)
	}

	if !sawSection {
		return nil, fmt.Errorf("no %q section found in the help text", "Commands:")
	}
	sort.Strings(out)
	return out, nil
}
