// Command ob-docgen writes the generated half of the documentation site.
//
// Three references in this product are already enumerated in Go, drift-tested,
// and published: the project-file schema, the loader's error codes, and the
// lifecycle failure contract. Writing them again by hand in Markdown would
// create a second source that can disagree with the first, and a published
// contract that disagrees with the loader is worse than none — it teaches the
// author something untrue and they learn to ignore it.
//
// So this program is the only writer of everything under
// `site/src/content/docs/reference/fields/`, `reference/errors`, and
// `reference/cli`. Those files carry a generated marker, and `--check` fails
// when what is on disk differs from what the current binary would produce.
// That turns "the documentation is current" into a build result rather than a
// claim.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/labstack/onebox/internal/app"
	"github.com/labstack/onebox/internal/onebox"
)

// MDX parses HTML comments as JSX, so the marker uses the MDX comment form.
const generatedMarker = "{/* Generated by cmd/ob-docgen. Do not edit by hand. */}"

func main() {
	var (
		out    string
		public string
		obBin  string
		check  bool
	)
	flag.StringVar(&out, "out", "site/src/content/docs/reference", "directory to write generated reference pages into")
	flag.StringVar(&public, "public", "site/public", "directory to publish machine-readable artifacts into")
	flag.StringVar(&obBin, "ob", "", "path to a built ob binary, for the CLI reference (default: look on PATH)")
	flag.BoolVar(&check, "check", false, "fail if the files on disk differ from what would be generated")
	flag.Parse()

	files, err := generate(obBin)
	if err != nil {
		fmt.Fprintln(os.Stderr, "ob-docgen:", err)
		os.Exit(1)
	}

	// The site publishes the schema it documents. Copying the checked-in file
	// would create a third copy that can disagree with the loader, so it is
	// produced from the same call `ob schema` makes.
	schema, err := app.JSONSchema()
	if err != nil {
		fmt.Fprintln(os.Stderr, "ob-docgen:", err)
		os.Exit(1)
	}
	schema = append(schema, '\n')
	publicFiles := map[string]string{"onebox.run-v1.schema.json": string(schema)}

	if check {
		if err := verify(out, files); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
		if err := verify(public, publicFiles); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
		fmt.Printf("ob-docgen: %d generated page(s) and %d published artifact(s) are current\n", len(files), len(publicFiles))
		return
	}

	for name, body := range publicFiles {
		path := filepath.Join(public, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
	}

	for name, body := range files {
		path := filepath.Join(out, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen:", err)
			os.Exit(1)
		}
	}
	fmt.Printf("ob-docgen: wrote %d page(s) to %s\n", len(files), out)
}

func verify(out string, want map[string]string) error {
	var stale []string
	for name, body := range want {
		got, err := os.ReadFile(filepath.Join(out, name))
		if err != nil {
			stale = append(stale, name+" (missing)")
			continue
		}
		if string(got) != body {
			stale = append(stale, name)
		}
	}
	if len(stale) > 0 {
		sort.Strings(stale)
		return fmt.Errorf("generated documentation is stale — run `just docs-generate`:\n  %s", strings.Join(stale, "\n  "))
	}
	return nil
}

func generate(obBin string) (map[string]string, error) {
	files := map[string]string{}

	schema, err := loadSchema()
	if err != nil {
		return nil, err
	}
	fieldPages, err := renderFieldPages(schema)
	if err != nil {
		return nil, err
	}
	for name, body := range fieldPages {
		files[name] = body
	}

	files["errors.mdx"] = renderErrorPage()

	cli, err := renderCLIPage(obBin)
	if err != nil {
		return nil, err
	}
	if cli != "" {
		files["cli.mdx"] = cli
	}

	return files, nil
}

// ---------------------------------------------------------------- schema ---

func loadSchema() (map[string]any, error) {
	body, err := app.JSONSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot produce the JSON Schema: %w", err)
	}
	var schema map[string]any
	if err := json.Unmarshal(body, &schema); err != nil {
		return nil, fmt.Errorf("cannot decode the JSON Schema: %w", err)
	}
	return schema, nil
}

// field is one row of a reference table: a dotted path, its type, its default
// and its description, flattened out of the schema's nesting.
type field struct {
	Path        string
	Type        string
	Enum        []string
	Default     string
	Description string
	Required    bool
}

// block is one generated page: a top-level key and every field beneath it.
type block struct {
	Key      string
	Title    string
	Summary  string
	Status   string
	ReadWhen []string
	Order    int
	Fields   []field
}

// The blocks that get their own page, in the order a reader meets them.
// A key absent from here still appears, on the top-level page, so a new field
// in the Go model can never silently vanish from the documentation.
var blocks = []block{
	{Key: "workloads", Title: "workloads", Order: 10, Status: "shipped",
		Summary: "The containers that are yours: their role, source, health, routing, prerequisites and container controls.",
		ReadWhen: []string{
			"Declaring an application, worker, daemon or job",
			"Choosing between image, build and compose as a workload source",
			"Setting replicas, resources, volumes, published ports or drain behaviour",
		}},
	{Key: "services", Title: "services", Order: 20, Status: "shipped",
		Summary: "Supporting services Onebox runs for you — the eleven built-in drivers, their versions, settings and persistence.",
		ReadWhen: []string{
			"Adding a database, cache or queue",
			"Deciding between a managed service and a daemon workload",
		}},
	{Key: "environments", Title: "environments", Order: 30, Status: "shipped",
		Summary: "Where the application runs, the SSH target, per-environment overrides, and the policy governing deployment there.",
		ReadWhen: []string{
			"Adding a staging or production environment",
			"Requiring approval, a minimum runner version, or migration backup evidence",
			"Working out which fields an environment override may change",
		}},
	{Key: "runtime", Title: "runtime", Order: 40, Status: "shipped",
		Summary: "Project-wide environment files and the local preflight assertions checked before a target is contacted.",
		ReadWhen: []string{
			"Wiring up environment files or SOPS-encrypted entries",
			"Requiring keys to be present before a deploy is attempted",
		}},
	{Key: "deployment", Title: "deployment", Order: 50, Status: "shipped",
		Summary: "Release ordering, how many releases are retained for rollback, and the migration policy.",
		ReadWhen: []string{"Changing release order, retention or migration gating"}},
	{Key: "verification", Title: "verification", Order: 60, Status: "shipped",
		Summary: "What must be true before a release becomes current: external URLs, in-workload checks, or migration revision evidence.",
		ReadWhen: []string{"Gating release activation on a health endpoint or a smoke test"}},
	{Key: "proxy", Title: "proxy", Order: 70, Status: "shipped",
		Summary: "Who owns the ingress proxy, which image runs it, and how TLS is resolved.",
		ReadWhen: []string{"Taking over the Traefik configuration, or turning routing off entirely"}},
	{Key: "hooks", Title: "hooks", Order: 80, Status: "shipped",
		Summary: "Commands run at lifecycle seams: pre_deploy, post_deploy, pre_rollback, post_rollback.",
		ReadWhen: []string{"Running a command around a deploy or a rollback"}},
	{Key: "registries", Title: "registries", Order: 90, Status: "shipped",
		Summary: "Named container registries and the local environment variables holding their credentials.",
		ReadWhen: []string{"Pulling from a private registry"}},
	{Key: "notifications", Title: "notifications", Order: 100, Status: "shipped",
		Summary: "Named webhooks that receive selected operation outcomes.",
		ReadWhen: []string{"Sending deploy outcomes to Slack, Discord or an incident tool"}},
	{Key: "observability", Title: "observability", Order: 110, Status: "intent-only",
		Summary: "Declared logging, metric and alerting intent. Validated and planned, but the local engine runs nothing continuous for it.",
		ReadWhen: []string{"Recording observability intent that another system will act on"}},
	{Key: "backup_targets", Title: "backup_targets", Order: 200, Status: "schema-only",
		Summary: "User-owned off-host S3-compatible repositories available to service protection policies. Accepted by the loader; not yet executable.",
		ReadWhen: []string{"Evaluating the proposed protection layer", "Understanding why Onebox refuses a backup target that shares the protected host"}},
	{Key: "external_services", Title: "external_services", Order: 210, Status: "schema-only",
		Summary: "Typed dependencies operated outside Onebox, whose lifecycle and protection stay external. Accepted by the loader; not yet executable.",
		ReadWhen: []string{"Modelling an RDS, Neon, Supabase or Upstash dependency"}},
}

func renderFieldPages(schema map[string]any) (map[string]string, error) {
	props, _ := schema["properties"].(map[string]any)
	if props == nil {
		return nil, fmt.Errorf("the JSON Schema has no top-level properties")
	}
	required := stringSet(schema["required"])

	byKey := map[string]*block{}
	for i := range blocks {
		byKey[blocks[i].Key] = &blocks[i]
	}

	// Anything not claimed by a block lands on the top-level page. A new field
	// in the Go model therefore appears in the documentation without anyone
	// remembering to add it.
	top := &block{
		Key: "top-level", Title: "Top level", Order: 1, Status: "shipped",
		Summary: "Required keys, project-wide scalars, and the single-workload shorthand.",
		ReadWhen: []string{
			"Starting a new project file",
			"Working out which keys are required",
		},
	}

	for name, raw := range props {
		node, _ := raw.(map[string]any)
		if node == nil {
			continue
		}
		target := byKey[name]
		if target == nil {
			target = top
			target.Fields = append(target.Fields, field{
				Path:        name,
				Type:        typeOf(node),
				Enum:        enumOf(node),
				Default:     defaultOf(node),
				Description: descriptionOf(node),
				Required:    required[name],
			})
			continue
		}
		target.Fields = append(target.Fields, walk(node, "", 0)...)
	}

	pages := map[string]string{}
	all := append([]*block{top}, func() []*block {
		var out []*block
		for i := range blocks {
			out = append(out, &blocks[i])
		}
		return out
	}()...)

	for _, b := range all {
		sort.SliceStable(b.Fields, func(i, j int) bool { return b.Fields[i].Path < b.Fields[j].Path })
		name := "fields/" + b.Key + ".mdx"
		pages[name] = renderBlockPage(b)
	}
	return pages, nil
}

// walk flattens a schema node into dotted field paths. It follows the three
// shapes this schema actually uses: object properties, an `additionalProperties`
// map keyed by a user-chosen name, and arrays of objects. The scalar shorthand
// forms appear as `oneOf` branches, which are merged rather than listed, since
// an author wants one row per field, not one row per accepted spelling.
func walk(node map[string]any, prefix string, depth int) []field {
	if depth > 4 {
		return nil
	}
	node = collapse(node)

	if items, ok := node["items"].(map[string]any); ok {
		return walk(items, prefix+"[]", depth)
	}

	if props, ok := node["properties"].(map[string]any); ok {
		required := stringSet(node["required"])
		var out []field
		names := make([]string, 0, len(props))
		for name := range props {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			child, _ := props[name].(map[string]any)
			if child == nil {
				continue
			}
			path := name
			if prefix != "" {
				path = prefix + "." + name
			}
			child = collapse(child)
			nested := walk(child, path, depth+1)
			out = append(out, field{
				Path:        path,
				Type:        typeOf(child),
				Enum:        enumOf(child),
				Default:     defaultOf(child),
				Description: descriptionOf(child),
				Required:    required[name],
			})
			out = append(out, nested...)
		}
		return out
	}

	if extra, ok := node["additionalProperties"].(map[string]any); ok {
		next := prefix + ".<name>"
		if prefix == "" {
			next = "<name>"
		}
		return walk(extra, next, depth)
	}

	return nil
}

// collapse merges the branches of a oneOf/anyOf/allOf into one node. The scalar
// shorthands are the reason these exist — `image: nginx` and
// `image: {reference: nginx}` are the same field written two ways — so the
// richest branch is what an author needs to see.
func collapse(node map[string]any) map[string]any {
	for _, key := range []string{"allOf", "oneOf", "anyOf"} {
		branches, ok := node[key].([]any)
		if !ok {
			continue
		}
		merged := map[string]any{}
		for k, v := range node {
			if k == key {
				continue
			}
			merged[k] = v
		}
		for _, raw := range branches {
			branch, ok := raw.(map[string]any)
			if !ok {
				continue
			}
			branch = collapse(branch)
			for k, v := range branch {
				if _, taken := merged[k]; !taken {
					merged[k] = v
				}
			}
		}
		return merged
	}
	return node
}

func typeOf(node map[string]any) string {
	node = collapse(node)
	if len(enumOf(node)) > 0 {
		return "enum"
	}
	switch t := node["type"].(type) {
	case string:
		if t == "array" {
			return "list"
		}
		if t == "object" {
			if _, keyed := node["additionalProperties"].(map[string]any); keyed {
				return "map"
			}
			return "object"
		}
		return t
	case []any:
		var parts []string
		for _, v := range t {
			if s, ok := v.(string); ok && s != "null" {
				parts = append(parts, s)
			}
		}
		return strings.Join(parts, " · ")
	}
	if _, ok := node["properties"]; ok {
		return "object"
	}
	return ""
}

func enumOf(node map[string]any) []string {
	raw, ok := node["enum"].([]any)
	if !ok {
		return nil
	}
	var out []string
	for _, v := range raw {
		out = append(out, fmt.Sprint(v))
	}
	return out
}

func defaultOf(node map[string]any) string {
	v, ok := node["default"]
	if !ok {
		return ""
	}
	return fmt.Sprint(v)
}

func descriptionOf(node map[string]any) string {
	s, _ := node["description"].(string)
	return strings.TrimSpace(s)
}

func stringSet(raw any) map[string]bool {
	out := map[string]bool{}
	list, ok := raw.([]any)
	if !ok {
		return out
	}
	for _, v := range list {
		if s, ok := v.(string); ok {
			out[s] = true
		}
	}
	return out
}

func renderBlockPage(b *block) string {
	var buf bytes.Buffer

	fmt.Fprintln(&buf, "---")
	fmt.Fprintf(&buf, "title: %s\n", jsonString(b.Title))
	fmt.Fprintf(&buf, "description: %s\n", jsonString(b.Summary))
	fmt.Fprintf(&buf, "summary: %s\n", jsonString(b.Summary))
	fmt.Fprintf(&buf, "status: %s\n", b.Status)
	fmt.Fprintln(&buf, "generated: true")
	fmt.Fprintf(&buf, "sidebar:\n  order: %d\n", b.Order)
	if len(b.ReadWhen) > 0 {
		fmt.Fprintln(&buf, "read_when:")
		for _, when := range b.ReadWhen {
			fmt.Fprintf(&buf, "  - %s\n", jsonString(when))
		}
	}
	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, generatedMarker)
	fmt.Fprintln(&buf)

	switch b.Status {
	case "schema-only":
		fmt.Fprintln(&buf, ":::caution[Accepted, not yet executable]")
		fmt.Fprintln(&buf, "The loader validates this block and it is published in the JSON Schema, so your")
		fmt.Fprintln(&buf, "editor will complete it. The behaviour behind it is an open proposal. Declaring")
		fmt.Fprintln(&buf, "it changes nothing on the target.")
		fmt.Fprintln(&buf, ":::")
		fmt.Fprintln(&buf)
	case "intent-only":
		fmt.Fprintln(&buf, ":::note[Intent only]")
		fmt.Fprintln(&buf, "These values are validated and carried into plans, but the local engine runs no")
		fmt.Fprintln(&buf, "continuous collectors or alert managers. Status reports them as declared, not")
		fmt.Fprintln(&buf, "managed.")
		fmt.Fprintln(&buf, ":::")
		fmt.Fprintln(&buf)
	}

	fmt.Fprintln(&buf, "This page is generated from the same Go declarations the loader enforces, so it")
	fmt.Fprintln(&buf, "cannot drift from what `ob validate` accepts.")
	fmt.Fprintln(&buf)

	if len(b.Fields) == 0 {
		fmt.Fprintln(&buf, "This block declares no fields.")
		return buf.String()
	}

	// Every row is a dotted path, so the bare field name is never a token on
	// its own. Site search then ranks a passing mention in a guide above the
	// reference page that actually defines the field — and for a name used
	// nowhere else, returns nothing at all. This index gives each leaf name one
	// clean occurrence, and doubles as a way to skim an eighty-row page.
	if names := leafNames(b.Fields); len(names) > 0 {
		fmt.Fprintln(&buf, "## Fields on this page")
		fmt.Fprintln(&buf)
		quoted := make([]string, 0, len(names))
		for _, name := range names {
			quoted = append(quoted, "`"+name+"`")
		}
		fmt.Fprintln(&buf, strings.Join(quoted, " · "))
		fmt.Fprintln(&buf)
		fmt.Fprintln(&buf, "## Reference")
		fmt.Fprintln(&buf)
	}

	fmt.Fprintln(&buf, "| Field | Type | Default | What it does |")
	fmt.Fprintln(&buf, "| --- | --- | --- | --- |")
	for _, f := range b.Fields {
		fmt.Fprintf(&buf, "| `%s`%s | %s | %s | %s |\n",
			f.Path,
			requiredMark(f.Required),
			typeCell(f),
			defaultCell(f),
			escapeCell(f.Description),
		)
	}
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "`*` marks a required field.")

	return buf.String()
}

// leafNames reduces the dotted paths to the distinct field names an author
// would actually search for, dropping the `<name>` map placeholder and the
// `[]` array marker that carry no meaning on their own.
func leafNames(fields []field) []string {
	seen := map[string]bool{}
	var out []string
	for _, f := range fields {
		parts := strings.Split(f.Path, ".")
		leaf := strings.TrimSuffix(parts[len(parts)-1], "[]")
		if leaf == "" || leaf == "<name>" || seen[leaf] {
			continue
		}
		seen[leaf] = true
		out = append(out, leaf)
	}
	sort.Strings(out)
	return out
}

func requiredMark(required bool) string {
	if required {
		return " `*`"
	}
	return ""
}

func typeCell(f field) string {
	if len(f.Enum) > 0 {
		quoted := make([]string, 0, len(f.Enum))
		for _, v := range f.Enum {
			quoted = append(quoted, "`"+v+"`")
		}
		return strings.Join(quoted, " · ")
	}
	if f.Type == "" {
		return "—"
	}
	return f.Type
}

func defaultCell(f field) string {
	if f.Default == "" {
		return "—"
	}
	return "`" + f.Default + "`"
}

func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.Join(strings.Fields(s), " ")
	if s == "" {
		return "—"
	}
	return s
}

func jsonString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

// ---------------------------------------------------------------- errors ---

func renderErrorPage() string {
	var buf bytes.Buffer

	summary := "Every typed failure code Onebox can emit: the loader's validation codes and the lifecycle failure contract, each with its meaning and resolving command."

	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf, `title: Error codes`)
	fmt.Fprintf(&buf, "description: %s\n", jsonString(summary))
	fmt.Fprintf(&buf, "summary: %s\n", jsonString(summary))
	fmt.Fprintln(&buf, "status: shipped")
	fmt.Fprintln(&buf, "generated: true")
	fmt.Fprintln(&buf, "sidebar:\n  order: 300")
	fmt.Fprintln(&buf, "read_when:")
	fmt.Fprintln(&buf, `  - "A command failed and you have a code but not a cause"`)
	fmt.Fprintln(&buf, `  - "Branching on a failure programmatically instead of parsing a message"`)
	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, generatedMarker)
	fmt.Fprintln(&buf)

	fmt.Fprintln(&buf, "A code is a promise: it names a kind of failure that keeps meaning the same thing")
	fmt.Fprintln(&buf, "across releases. Branch on the code, never on the sentence.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "Adding one is a deliberate act. A test refuses any code the loader emits that is")
	fmt.Fprintln(&buf, "not enumerated, and any enumerated code that nothing emits, so this list cannot")
	fmt.Fprintln(&buf, "drift in either direction.")
	fmt.Fprintln(&buf)

	fmt.Fprintln(&buf, "## Validation codes")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "Emitted while loading and checking the project file. Each failure carries the")
	fmt.Fprintln(&buf, "code, the path that produced it, and where possible the line and the resolving")
	fmt.Fprintln(&buf, "command.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "| Code | Means |")
	fmt.Fprintln(&buf, "| --- | --- |")
	for _, code := range app.ErrorCodes() {
		meaning, _ := app.ErrorCodeMeaning(code)
		fmt.Fprintf(&buf, "| `%s` | %s |\n", code, escapeCell(meaning))
	}
	fmt.Fprintln(&buf)

	fmt.Fprintln(&buf, "## Lifecycle failure codes")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, ":::caution[Belongs to the proposed protection layer]")
	fmt.Fprintln(&buf, "These codes are defined and drift-tested in the binary, but the operations that")
	fmt.Fprintln(&buf, "raise most of them are not yet executable.")
	fmt.Fprintln(&buf, ":::")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "The failure contract shared by plans, event streams, terminal results, status and")
	fmt.Fprintln(&buf, "doctor. Each carries a stable code and a safe resolving command; diagnostic")
	fmt.Fprintln(&buf, "detail stays in restricted local evidence, never in the public record.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "| Code | Means | Resolving command |")
	fmt.Fprintln(&buf, "| --- | --- | --- |")
	for _, code := range onebox.LifecycleFailureCodes() {
		failure, err := onebox.NewLifecycleFailure(code)
		if err != nil {
			continue
		}
		fmt.Fprintf(&buf, "| `%s` | %s | `%s` |\n", code, escapeCell(failure.Message), failure.Next)
	}

	return buf.String()
}

// ------------------------------------------------------------------- CLI ---

// renderCLIPage asks the built binary to describe itself. The root command is
// unexported in package main, so shelling out is what keeps the CLI reference
// generated rather than transcribed. With no binary available the page is
// skipped rather than written stale.
func renderCLIPage(obBin string) (string, error) {
	if obBin == "" {
		found, err := exec.LookPath("ob")
		if err != nil {
			fmt.Fprintln(os.Stderr, "ob-docgen: no ob binary found, skipping the CLI reference (build it with `just build`)")
			return "", nil
		}
		obBin = found
	}

	root, err := help(obBin)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	summary := "Every ob command, its help text and its flags, taken from the binary itself."

	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf, "title: CLI commands")
	fmt.Fprintf(&buf, "description: %s\n", jsonString(summary))
	fmt.Fprintf(&buf, "summary: %s\n", jsonString(summary))
	fmt.Fprintln(&buf, "status: shipped")
	fmt.Fprintln(&buf, "generated: true")
	fmt.Fprintln(&buf, "sidebar:\n  order: 200")
	fmt.Fprintln(&buf, "read_when:")
	fmt.Fprintln(&buf, `  - "Looking up what a command does, or which flags it takes"`)
	fmt.Fprintln(&buf, `  - "Deciding whether a command contacts the target or changes it"`)
	fmt.Fprintln(&buf, "---")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, generatedMarker)
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "Generated from the binary, so it cannot describe a flag the CLI does not have.")
	fmt.Fprintln(&buf, "`ob <command> --help` is the same text.")
	fmt.Fprintln(&buf)

	fmt.Fprintln(&buf, "## ob")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "```")
	fmt.Fprintln(&buf, strings.TrimRight(root, "\n"))
	fmt.Fprintln(&buf, "```")
	fmt.Fprintln(&buf)

	for _, name := range subcommands(root) {
		body, err := help(obBin, strings.Fields(name)...)
		if err != nil {
			continue
		}
		fmt.Fprintf(&buf, "## ob %s\n\n", name)
		fmt.Fprintln(&buf, "```")
		fmt.Fprintln(&buf, strings.TrimRight(body, "\n"))
		fmt.Fprintln(&buf, "```")
		fmt.Fprintln(&buf)

		for _, nested := range subcommands(body) {
			full := name + " " + nested
			nestedBody, err := help(obBin, strings.Fields(full)...)
			if err != nil {
				continue
			}
			fmt.Fprintf(&buf, "### ob %s\n\n", full)
			fmt.Fprintln(&buf, "```")
			fmt.Fprintln(&buf, strings.TrimRight(nestedBody, "\n"))
			fmt.Fprintln(&buf, "```")
			fmt.Fprintln(&buf)
		}
	}

	return buf.String(), nil
}

func help(bin string, args ...string) (string, error) {
	cmd := exec.Command(bin, append(args, "--help")...)
	cmd.Env = append(os.Environ(), "NO_COLOR=1")
	var out, errOut bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &errOut
	if err := cmd.Run(); err != nil && out.Len() == 0 {
		return "", fmt.Errorf("ob %s --help: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(errOut.String()))
	}
	return out.String(), nil
}

// subcommands reads the "Available Commands:" section cobra prints. Parsing
// help output is coarse, but it is the only view of the command tree available
// from outside package main, and a missing command is visible rather than
// silent.
func subcommands(helpText string) []string {
	var out []string
	inSection := false
	for _, line := range strings.Split(helpText, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasSuffix(trimmed, "Commands:") {
			inSection = true
			continue
		}
		if inSection {
			if trimmed == "" {
				inSection = false
				continue
			}
			if !strings.HasPrefix(line, " ") {
				inSection = false
				continue
			}
			name := strings.Fields(trimmed)
			if len(name) == 0 {
				continue
			}
			if name[0] == "help" || name[0] == "completion" {
				continue
			}
			out = append(out, name[0])
		}
	}
	sort.Strings(out)
	return out
}
