// Package proxy renders and identifies the HOST-scoped managed proxy (design:
// "The proxy is owned — managed or external, never assumed"). One Traefik per
// host, shared by every ob app on it, living under /var/lib/ob/_host/ —
// a name no app can take (app names match ^[a-z][a-z0-9-]*$).
//
// The app supplies the Traefik configuration as a flat dir (proxy.config):
// traefik.yml required (static config; must declare ping: {} — the container
// healthcheck gates on it — and ACME storage at /letsencrypt/acme.json);
// dynamic.yml and .env optional. ob renders the compose around it.
package proxy

import (
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const (
	DefaultImage   = "traefik:v3.7"
	DefaultNetwork = "ob-ingress"
	// Project is the compose project name; ContainerName the fixed container
	// name — both host-global, which is the point.
	Project       = "ob-proxy"
	ContainerName = "ob-proxy"
)

// Paths is the host-scoped layout, sibling of the per-app dirs.
type Paths struct {
	Base      string // <root>/_host
	Lock      string // <root>/_host/lock
	Journal   string // <root>/_host/journal
	Dir       string // <root>/_host/proxy
	Compose   string // <root>/_host/proxy/compose.yaml
	ConfigDir string // <root>/_host/proxy/config
	Acme      string // <root>/_host/proxy/acme
	Apps      string // <root>/_host/proxy/apps
	Hash      string // <root>/_host/proxy/config.hash
}

func HostPaths() Paths {
	root := os.Getenv("OB_BASE_DIR") // same test hook as release.PathsFor
	if root == "" {
		root = "/var/lib/ob"
	}
	base := root + "/_host"
	return Paths{
		Base:      base,
		Lock:      base + "/lock",
		Journal:   base + "/journal",
		Dir:       base + "/proxy",
		Compose:   base + "/proxy/compose.yaml",
		ConfigDir: base + "/proxy/config",
		Acme:      base + "/proxy/acme",
		Apps:      base + "/proxy/apps",
		Hash:      base + "/proxy/config.hash",
	}
}

// RenderCompose emits the proxy's own compose file. Deliberately a template,
// not compose-go construction: the shape IS the contract and a reviewer should
// be able to read it whole.
func RenderCompose(image, network string, hasEnv bool) []byte {
	if image == "" {
		image = DefaultImage
	}
	if network == "" {
		network = DefaultNetwork
	}
	envFile := ""
	if hasEnv {
		envFile = "    env_file: [config/.env]\n"
	}
	return []byte(fmt.Sprintf(`# generated by onebox — do not edit (ob proxy apply owns this file)
services:
  proxy:
    container_name: %s
    image: %s
    restart: unless-stopped
    ports: ["80:80", "443:443"]
%s    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik:ro
      - ./acme:/letsencrypt
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks: [ingress]
networks:
  ingress:
    name: %s
`, ContainerName, image, envFile, network))
}

// CertExpiry is one issued certificate's identity and lifetime — the ONLY
// data status extracts from acme.json (which also holds private keys; those
// never leave the parse).
type CertExpiry struct {
	Domain   string
	NotAfter time.Time
}

// CertExpiries parses a lego/Traefik acme.json store and returns each
// certificate's main domain and expiry. An empty store (fresh acme.json is an
// empty file) returns nothing; malformed JSON errors so status can say so.
func CertExpiries(acmeJSON []byte) ([]CertExpiry, error) {
	if len(strings.TrimSpace(string(acmeJSON))) == 0 {
		return nil, nil
	}
	// lego layout: {"<resolver>": {"Certificates": [{"domain": {"main": ...},
	// "certificate": "<base64 PEM chain>", ...}]}}
	var store map[string]struct {
		Certificates []struct {
			Domain struct {
				Main string `json:"main"`
			} `json:"domain"`
			Certificate string `json:"certificate"`
		} `json:"Certificates"`
	}
	if err := json.Unmarshal(acmeJSON, &store); err != nil {
		return nil, fmt.Errorf("acme store: %w", err)
	}
	var out []CertExpiry
	for _, resolver := range store {
		for _, c := range resolver.Certificates {
			pemChain, err := base64.StdEncoding.DecodeString(c.Certificate)
			if err != nil {
				continue // account blocks etc. — not a certificate
			}
			block, _ := pem.Decode(pemChain)
			if block == nil || block.Type != "CERTIFICATE" {
				continue
			}
			cert, err := x509.ParseCertificate(block.Bytes)
			if err != nil {
				continue
			}
			out = append(out, CertExpiry{Domain: c.Domain.Main, NotAfter: cert.NotAfter})
		}
	}
	return out, nil
}

// Stage builds the local staging payload for the host proxy: compose.yaml +
// config/<the app's flat traefik dir>, and returns the payload hash — the
// identity used for cross-app conflict detection and change detection.
func Stage(localCfgDir, stagingDir, image, network string) (string, error) {
	entries, err := os.ReadDir(localCfgDir)
	if err != nil {
		return "", fmt.Errorf("proxy.config: %w", err)
	}
	names := make([]string, 0, len(entries))
	hasTraefik, hasEnv := false, false
	for _, e := range entries {
		if e.IsDir() {
			return "", fmt.Errorf("proxy.config must be a flat dir of config files; %s/ is a directory", e.Name())
		}
		names = append(names, e.Name())
		if e.Name() == "traefik.yml" {
			hasTraefik = true
		}
		if e.Name() == ".env" {
			hasEnv = true
		}
	}
	if !hasTraefik {
		return "", fmt.Errorf("proxy.config: traefik.yml required (static config; must enable ping: {} and store ACME at /letsencrypt/acme.json)")
	}
	sort.Strings(names)

	cfgOut := filepath.Join(stagingDir, "config")
	if err := os.MkdirAll(cfgOut, 0o755); err != nil {
		return "", err
	}
	h := sha256.New()
	for _, name := range names {
		b, err := os.ReadFile(filepath.Join(localCfgDir, name))
		if err != nil {
			return "", err
		}
		// .env may hold secrets (e.g. the DNS API token) — mode 600, same
		// trust boundary as the release payload's env files
		if err := os.WriteFile(filepath.Join(cfgOut, name), b, 0o600); err != nil {
			return "", err
		}
		fmt.Fprintf(h, "%s\x00%d\x00", name, len(b))
		h.Write(b)
	}
	compose := RenderCompose(image, network, hasEnv)
	if err := os.WriteFile(filepath.Join(stagingDir, "compose.yaml"), compose, 0o644); err != nil {
		return "", err
	}
	fmt.Fprintf(h, "compose.yaml\x00%d\x00", len(compose))
	h.Write(compose)
	return hex.EncodeToString(h.Sum(nil)), nil
}
